version: 2.1

executors:
  ubuntu_vm:
    machine:
      image: ubuntu-1604:201903-01
      docker_layer_caching: true

jobs:
  validate-template:
    executor: ubuntu_vm
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run: make validate

  deploy-stack:
    executor: ubuntu_vm
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run: make deploy

workflows:
  validate-deploy:
    jobs:
      - deploy-stack:
          requires:
            - validate-template
